const PatientDetails = [
  {
    memberId: 10001,
    memberName: "John Doe",
    address: "Chennai, India",
    email: "john.doe@example.com",
    phone_no: "9876543210",
    doctor: "Dr. Suzanne",
    vendor: "MinuteClinic (CVS Health)",
    aco: "Allina Health ACO",
    insurence_type: "Individual",
    primary_illness: "Heart Disease",
    do_not_call_list: "Yes",
    dateOfJoin: "12/01/2023",
    totalPremium: 1200,
    noOfClaims: 5,
    totalClaimAmount: 700,
  },
  {
    memberId: 10002,
    memberName: "Jane Smith",
    address: "Bangalore, India",
    email: "jane.smith@example.com",
    phone_no: "9123456780",
    doctor: "Dr. Peyton J",
    vendor: "Walgreens Healthcare Clinic",
    aco: "Baylor Scott & White Quality Alliance",
    insurence_type: "Employer Sponsored",
    primary_illness: "Cancer",
    do_not_call_list: "No",
    dateOfJoin: "11/15/2022",
    totalPremium: 1500,
    noOfClaims: 2,
    totalClaimAmount: 300,
  },
  {
    memberId: 10003,
    memberName: "Michael Brown",
    address: "Delhi, India",
    email: "michael.brown@example.com",
    phone_no: "9812345678",
    doctor: "Dr. Taylor, Jr.",
    vendor: "Concentra Urgent Care",
    aco: "Catholic Health Initiatives (CHI) ACO",
    insurence_type: "Medicare - Federal",
    primary_illness: "Diabetes",
    do_not_call_list: "Yes",
    dateOfJoin: "10/05/2021",
    totalPremium: 1800,
    noOfClaims: 4,
    totalClaimAmount: 900,
  },
  {
    memberId: 10004,
    memberName: "Lisa Ray",
    address: "Mumbai, India",
    email: "lisa.ray@example.com",
    phone_no: "9712345678",
    doctor: "Dr. Richard D. Pearson",
    vendor: "Duke University Health System",
    aco: "Essentia Health ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Kidney Disease",
    do_not_call_list: "No",
    dateOfJoin: "09/20/2020",
    totalPremium: 1300,
    noOfClaims: 3,
    totalClaimAmount: 500,
  },
  {
    memberId: 10005,
    memberName: "David Green",
    address: "Pune, India",
    email: "david.green@example.com",
    phone_no: "9612345678",
    doctor: "Dr. W. Michael Scheld",
    vendor: "UCLA Health",
    aco: "Mayo Clinic ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Musculoskeletal Disorders",
    do_not_call_list: "Yes",
    dateOfJoin: "08/15/2019",
    totalPremium: 1600,
    noOfClaims: 1,
    totalClaimAmount: 200,
  },
  {
    memberId: 10006,
    memberName: "Emma Wilson",
    address: "Hyderabad, India",
    email: "emma.wilson@example.com",
    phone_no: "9512345678",
    doctor: "Dr. James M. Larner",
    vendor: "",
    aco: "Kaiser Permanente ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Liver Disease",
    do_not_call_list: "No",
    dateOfJoin: "07/10/2018",
    totalPremium: 1100,
    noOfClaims: 2,
    totalClaimAmount: 400,
  },
  {
    memberId: 10007,
    memberName: "Sophia Johnson",
    address: "Ahmedabad, India",
    email: "sophia.johnson@example.com",
    phone_no: "9412345678",
    doctor: "Dr. Kenneth J. Cherry Jr.",
    vendor: "",
    aco: "UnityPoint Health ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Neurological Disorders",
    do_not_call_list: "Yes",
    dateOfJoin: "06/05/2017",
    totalPremium: 1400,
    noOfClaims: 3,
    totalClaimAmount: 600,
  },
  {
    memberId: 10008,
    memberName: "Oliver Brown",
    address: "Kolkata, India",
    email: "oliver.brown@example.com",
    phone_no: "9312345678",
    doctor: "Dr. Jerome M",
    vendor: "",
    aco: "",
    insurence_type: "Medicaid - State",
    primary_illness: "Unknown",
    do_not_call_list: "No",
    dateOfJoin: "05/01/2016",
    totalPremium: 1700,
    noOfClaims: 4,
    totalClaimAmount: 800,
  },
  {
    memberId: 10009,
    memberName: "Ethan Harris",
    address: "Chennai, India",
    email: "ethan.harris@example.com",
    phone_no: "9212345678",
    doctor: "Dr. Michael C. Lewis",
    vendor: "Apollo Clinic",
    aco: "Fortis Health ACO",
    insurence_type: "Individual",
    primary_illness: "Respiratory Disease",
    do_not_call_list: "Yes",
    dateOfJoin: "03/25/2019",
    totalPremium: 1350,
    noOfClaims: 2,
    totalClaimAmount: 450,
  },
  {
    memberId: 10010,
    memberName: "Grace Lee",
    address: "Bangalore, India",
    email: "grace.lee@example.com",
    phone_no: "9112345678",
    doctor: "Dr. Sarah K. Thomas",
    vendor: "Columbia Asia",
    aco: "Narayana Health ACO",
    insurence_type: "Employer Sponsored",
    primary_illness: "Gastrointestinal Disease",
    do_not_call_list: "No",
    dateOfJoin: "01/10/2021",
    totalPremium: 1550,
    noOfClaims: 3,
    totalClaimAmount: 600,
  },
  {
    memberId: 10011,
    memberName: "Daniel White",
    address: "Delhi, India",
    email: "daniel.white@example.com",
    phone_no: "9012345678",
    doctor: "Dr. William B. Davis",
    vendor: "Max Healthcare",
    aco: "Medanta ACO",
    insurence_type: "Medicare - Federal",
    primary_illness: "Cardiovascular Disease",
    do_not_call_list: "Yes",
    dateOfJoin: "02/20/2018",
    totalPremium: 1750,
    noOfClaims: 4,
    totalClaimAmount: 850,
  },
  {
    memberId: 10012,
    memberName: "Hannah Walker",
    address: "Mumbai, India",
    email: "hannah.walker@example.com",
    phone_no: "8912345678",
    doctor: "Dr. Nancy E. Carter",
    vendor: "Manipal Hospitals",
    aco: "Aster DM Healthcare ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Dermatological Disorders",
    do_not_call_list: "No",
    dateOfJoin: "07/15/2020",
    totalPremium: 1250,
    noOfClaims: 1,
    totalClaimAmount: 250,
  },
  {
    memberId: 10013,
    memberName: "Lucas Young",
    address: "Pune, India",
    email: "lucas.young@example.com",
    phone_no: "8812345678",
    doctor: "Dr. David J. Lee",
    vendor: "Ruby Hall Clinic",
    aco: "Jehangir Hospital ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Endocrine Disorders",
    do_not_call_list: "Yes",
    dateOfJoin: "06/05/2019",
    totalPremium: 1450,
    noOfClaims: 3,
    totalClaimAmount: 650,
  },
  {
    memberId: 10014,
    memberName: "Ella King",
    address: "Hyderabad, India",
    email: "ella.king@example.com",
    phone_no: "8712345678",
    doctor: "Dr. George K. Evans",
    vendor: "Yashoda Hospitals",
    aco: "CARE Hospitals ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Hematological Disorders",
    do_not_call_list: "No",
    dateOfJoin: "04/20/2018",
    totalPremium: 1650,
    noOfClaims: 2,
    totalClaimAmount: 500,
  },
  {
    memberId: 10015,
    memberName: "Mia Scott",
    address: "Ahmedabad, India",
    email: "mia.scott@example.com",
    phone_no: "8612345678",
    doctor: "Dr. Elizabeth H. Mitchell",
    vendor: "Shalby Hospitals",
    aco: "Sterling Hospitals ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Immunological Disorders",
    do_not_call_list: "Yes",
    dateOfJoin: "03/15/2017",
    totalPremium: 1150,
    noOfClaims: 4,
    totalClaimAmount: 750,
  },
  {
    memberId: 10016,
    memberName: "Ava Davis",
    address: "Kolkata, India",
    email: "ava.davis@example.com",
    phone_no: "8512345678",
    doctor: "Dr. Steven R. Martinez",
    vendor: "AMRI Hospitals",
    aco: "Apollo Gleneagles Hospitals ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Infectious Diseases",
    do_not_call_list: "No",
    dateOfJoin: "02/10/2016",
    totalPremium: 1950,
    noOfClaims: 5,
    totalClaimAmount: 950,
  },
  {
    memberId: 10017,
    memberName: "Jack Martinez",
    address: "Chennai, India",
    email: "jack.martinez@example.com",
    phone_no: "8412345678",
    doctor: "Dr. Laura M. Perez",
    vendor: "SRM Hospital",
    aco: "PSG Hospitals ACO",
    insurence_type: "Individual",
    primary_illness: "Metabolic Disorders",
    do_not_call_list: "Yes",
    dateOfJoin: "01/01/2015",
    totalPremium: 1850,
    noOfClaims: 3,
    totalClaimAmount: 700,
  },
  {
    memberId: 10018,
    memberName: "Lily Hernandez",
    address: "Bangalore, India",
    email: "lily.hernandez@example.com",
    phone_no: "8312345678",
    doctor: "Dr. Kimberly R. Gonzalez",
    vendor: "St. John's Hospital",
    aco: "Manipal Hospitals ACO",
    insurence_type: "Employer Sponsored",
    primary_illness: "Neurological Disorders",
    do_not_call_list: "No",
    dateOfJoin: "11/20/2014",
    totalPremium: 1750,
    noOfClaims: 2,
    totalClaimAmount: 500,
  },
  {
    memberId: 10019,
    memberName: "James Robinson",
    address: "Delhi, India",
    email: "james.robinson@example.com",
    phone_no: "8212345678",
    doctor: "Dr. Kevin M. Young",
    vendor: "BLK Super Speciality Hospital",
    aco: "Medanta ACO",
    insurence_type: "Medicare - Federal",
    primary_illness: "Pulmonary Disease",
    do_not_call_list: "Yes",
    dateOfJoin: "05/15/2013",
    totalPremium: 1650,
    noOfClaims: 1,
    totalClaimAmount: 300,
  },
  {
    memberId: 10020,
    memberName: "Emily Clark",
    address: "Mumbai, India",
    email: "emily.clark@example.com",
    phone_no: "8112345678",
    doctor: "Dr. Anthony S. Harris",
    vendor: "SevenHills Hospital",
    aco: "Aster DM Healthcare ACO",
    insurence_type: "Medicaid - State",
    primary_illness: "Renal Disease",
    do_not_call_list: "No",
    dateOfJoin: "07/10/2012",
    totalPremium: 1550,
    noOfClaims: 3,
    totalClaimAmount: 600,
  },
];

// const CreateTableWithColoumns = `
//     CREATE TABLE IF NOT EXISTS PatientDetails (
//     "memberId" VARCHAR(100),
//     "memberName" VARCHAR(100),
//     "address" VARCHAR(100),
//     "email" VARCHAR(100),
//     "phone_no" VARCHAR(100),
//     "doctor" VARCHAR(100),
//     "vendor" VARCHAR(100),
//     "aco" VARCHAR(100),
//     "insurence_type" VARCHAR(100),
//     "primary_illness" VARCHAR(100),
//     "do_not_call_list" VARCHAR(100),
//     "dateOfJoin" DATE,
//     "totalPremium" DECIMAL(10,2),
//     "noOfClaims" INTEGER,
//     "totalClaimAmount" DECIMAL(10,2));
//   `;

const CreateTableWithColoumns = `
  CREATE TABLE PatientDetails (
    memberId INT PRIMARY KEY,
    memberName VARCHAR(100),
    address VARCHAR(255),
    email VARCHAR(100),
    phone_no VARCHAR(20),
    doctor VARCHAR(100),
    vendor VARCHAR(100),
    aco VARCHAR(100),
    insurence_type VARCHAR(50),
    primary_illness VARCHAR(100),
    do_not_call_list VARCHAR(10),
    dateOfJoin DATE,
    totalPremium INT,
    noOfClaims INT,
    totalClaimAmount INT
);
`;

// const addData = (patientDetail) => {
//   const fields = Object.keys(patientDetail);
//   const values = Object.values(patientDetail);
//   const addDataQuery = `INSERT INTO PatientDetails(${fields.join(
//     ", "
//   )}) VALUES (${values.map((value) => `'${value}'`).join(", ")})`;
//   return addDataQuery;
// };
const addData = (patientDetail) => {
  const fields = Object.keys(patientDetail);
  const values = Object.values(patientDetail).map(value => typeof value === 'string' ? `'${value.replace(/'/g, "''")}'` : value); // Handle single quotes in string values
  const addDataQuery = `INSERT INTO PatientDetails(${fields.join(", ")}) VALUES (${values.join(", ")});`;
  return addDataQuery;
};

// const fields = Object.keys(PatientDetails);
// const values = Object.values(PatientDetails);

// const addDataQuery = `INSERT INTO PatientDetails(${fields.join(
//   ", "
// )}) VALUES (${values.map((value) => `'${value}'`).join(", ")})`;

const getData = `SELECT * FROM PatientDetails`;

module.exports = {
  PatientDetails,
  CreateTableWithColoumns,
  getData,
  addData,
};
